name: book-box-hardcover
author: Anthony Morris <anthony@amorrissound.com>
description: Update a pinned gist to contain your latest reads on Hardcover.app
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'book-open'
  color: 'green'
