on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight UTC
  workflow_dispatch:  # Allow manual trigger
name: Update gist with latest hardcover.app 
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: update-gist
        uses: DoguD/book-box-hardcover@master
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          HARDCOVER_KEY: ${{ secrets.HARDCOVER_KEY }}
